openapi: 3.0.1
info:
  title: UMANG NEILT API v1.1
  description: |-
      National Institute of Electronics & Information Technology (NIELIT),(erstwhile DOEACC Society), an Autonomous Scientific Society under the administrative control of Ministry of Electronics & Information Technology (MoE&IT), Government of India, was set up to carry out Human Resource Development and related activities in the area of Information, Electronics & Communications Technology (IECT). NIELIT is engaged both in Formal & Non-Formal Education in the area of IECT besides development of industry oriented quality education and training programmes in the state-of-the-art areas. NIELIT has endeavoured to establish standards to be the country’s premier institution for Examination and Certification in the field of IECT. It is also one of the National Examination Body, which accredits institutes/organizations for conducting courses in IT in the non-formal sector.
  termsOfService: https://web.umang.gov.in/
  contact:
    name: UMANG NEILT API v1.1
    url: https://web.umang.gov.in/customer_support
  version: 1.0.0
servers:
- url: https://app.umang.gov.in/t/negd.gov.in/umang/depttapi/NEILTApi/ws1/1.0
paths:
  /TrgCalendar:
    post:
      tags:
      - Get Trg Calendar
      summary: This API will be used to get Trg Calendar.
      operationId: TrgCalendar
      security:
      - bearerAuth: []
      parameters:
        - in: header
          name: deptid
          schema:
            type: integer
            example: 321
        - in: header
          name: srvid
          schema:
            type: integer
            example: 1390
        - in: header
          name: subsid
          schema:
            type: integer
            example: 0
        - in: header
          name: subsid2
          schema:
            type: integer
            example: 0
        - in: header
          name: formtrkr
          schema:
            type: integer
            example: 0

      requestBody:
        content:
          application/json:
            schema:
              anyOf:
              - $ref: "#/components/schemas/req_Aadhar_Not_Linked"
              - $ref: "#/components/schemas/req_Aadhar_Not_Available"
            examples:
              Aadhar_Not_Linked:
                $ref: "#/components/examples/req_Aadhar_Not_Linked"
              Aadhar_Not_Available:
                $ref: "#/components/examples/req_Aadhar_Not_Available"
      
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - $ref: "#/components/schemas/Aadhar_Not_Linked"
                - $ref: "#/components/schemas/Aadhar_Not_Available"
              examples:
                Aadhar_Not_Linked:
                  $ref: "#/components/examples/Aadhar_Not_Linked"
                Aadhar_Not_Available:
                  $ref: "#/components/examples/Aadhar_Not_Available"

            application/xml:
              schema:
                  $ref: '#/components/schemas/book'
   
        400:
          description: Bad Request/Validation Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Text


  schemas:
#RequestBody Schemas#
    req_Aadhar_Not_Linked:
      properties:
        rs:
          type: string
        rc:
          type: string
        rd:
          type: string
        pd:
          type: object
    req_Aadhar_Not_Available:
      properties:
        rs:
          type: string
        rc:
          type: string
        rd:
          type: string
        pd:
          type: object
#End of RequestBody Schemas#
#Response Schemas#
    Aadhar_Not_Linked:
      properties:
        rs:
          type: string
        rc:
          type: string
        rd:
          type: string
        pd:
          type: object
    Aadhar_Not_Available:
      properties:
        rs:
          type: string
        rc:
          type: string
        rd:
          type: string
        pd:
          type: object

    book:
      type: object
      properties:
          id1:
            $ref: '#/components/schemas/id1'
          xml-title1:
            $ref: '#/components/schemas/xml-title1'
          author1:
            $ref: '#/components/schemas/author1'
          lang1:
            $ref: '#/components/schemas/lang1'

     
    id1:
      #no children
      type: integer
      properties: {}
      example: 0
      xml:
        wrapped: true
        name: 'id'
     
    xml-title1:
      #no children
      type: string
      properties: {}
      example: "string"
      xml:
        wrapped: true
        name: 'xml-title'
     
    author1:
      #no children
      type: string
      properties: {}
      example: "string"
      xml:
        wrapped: true
        name: 'author'
     
    lang1:
      #no children
      type: string
      properties: {}
      example: "আপনার দিনটি শুভ হোক"
      xml:
        wrapped: true
        name: 'lang'

#End of Response Schemas#
  examples:
#RequestBody Examples#
    req_Aadhar_Not_Linked:
      value:
        rs: S
        rc: 200
        rd: Success.
        pd: {'restServiceMessage': {'serviceCallFlag': 'Y', 'serviceDataFoundFlag': 'N', 'serviceMessage': 'Aadhar Not Linked !!!'}}
    req_Aadhar_Not_Available:
      value:
        rs: S12
        rc: 200
        rd: Success.
        pd: {'restServiceMessage': {'serviceCallFlag': 'Y', 'serviceDataFoundFlag': 'N', 'serviceMessage': 'Aadhar Not Available !!!'}}
#End of RequestBody Examples#
#Response Examples#
    Aadhar_Not_Linked:
      value:
        rs: S
        rc: 200
        rd: Success.
        pd: {'restServiceMessage': {'serviceCallFlag': 'Y', 'serviceDataFoundFlag': 'N', 'serviceMessage': 'Aadhar Not Linked !!!'}}
    Aadhar_Not_Available:
      value:
        rs: S12
        rc: 200
        rd: Success.
        pd: {'restServiceMessage': {'serviceCallFlag': 'Y', 'serviceDataFoundFlag': 'N', 'serviceMessage': 'Aadhar Not Available !!!'}}

#End of Response Examples